### ISSUE TITLE
When using role 2 times checksums are not loaded again

### ISSUE THREAD

**Issue by arolfes** [arolfes/ansible-role-graalvm#4]
```yaml
    - role: arolfes.graalvm
      graalvm_java_version: '8'
      graalvm_is_default_installation: false
      graalvm_fact_group_name: 'graalvm-java8'

    - role: arolfes.graalvm
```
the second role should install graalvm java11 but checksum is skipped...
